version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - microservices-network

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - microservices-network
    restart: unless-stopped

  permission-service:
    build: ./permission-service
    container_name: permission-service
    ports:
      - "${PERMISSION_SERVICE_PORT}:${PERMISSION_SERVICE_PORT}"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - microservices-network
    restart: unless-stopped

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    depends_on:
      - user-service
      - permission-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  mongo-data:
